# Generated by Django 5.0 on 2023-12-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moneytype_alter_product_options_product_moneytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='moneytype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneytype'),
        ),
    ]
