# Generated by Django 5.0 on 2024-01-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_photo_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='src',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
