# Generated by Django 5.0 on 2024-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productcategory_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='src',
            field=models.CharField(max_length=100),
        ),
    ]
