# Generated by Django 5.0 on 2024-01-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productcategory_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='moneytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moneytype'),
        ),
    ]
