# Generated by Django 5.0 on 2024-01-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_category_alter_product_moneytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='src',
        ),
    ]
